"""NetFlip package."""

from importlib.metadata import PackageNotFoundError, version

from netflip.benchmarks import (
    CifarResNet20ArtifactPreparationOutput,
    CifarResNet20QuantizedArtifact,
    PerTensorScale,
    PerTensorScaleMetadata,
    load_cifar_resnet20_quantized_artifact,
    load_per_tensor_scale_metadata,
    prepare_cifar_resnet20_artifacts,
    quantize_cifar_resnet20_state_dict,
    write_per_tensor_scale_metadata,
)
from netflip.bfa_pbs import (
    ATTACK_BUDGET_STOP_REASON,
    ATTACK_SCENARIO_TYPE,
    BFA_PBS_STRATEGY_NAME,
    ELIGIBLE_BITS_EXHAUSTED_STOP_REASON,
    GROUND_TRUTH_TARGET_POLICY,
    MAXIMIZE_CROSS_ENTROPY_OBJECTIVE,
    NO_IMPROVING_CANDIDATE_STOP_REASON,
    BfaPbsCandidatePlan,
    BfaPbsCandidateScore,
    BfaPbsRunResult,
    ObjectiveEvaluator,
    run_bfa_pbs_attack_strategy,
    score_bfa_pbs_candidates,
    validate_bfa_pbs_scenario_config,
)
from netflip.experiment_spec import (
    EXPERIMENT_SPEC_SCHEMA_VERSION,
    BenchmarkModelSpec,
    BfaPbsScenarioSpec,
    CheckpointSpec,
    DatasetSpec,
    ExperimentSpec,
    FaultBudgetSpec,
    QuantizationSpec,
    RandomSoftErrorScenarioSpec,
    load_experiment_spec,
    parse_experiment_spec,
)
from netflip.int8_codec import (
    INT8_BIT_WIDTH,
    INT8_MAX,
    INT8_MIN,
    INT8_MODULUS,
    INT8_SIGN_BIT_MASK,
    UINT8_MAX,
    BitMetadata,
    BitRole,
    SignedInt8TwoComplementCodec,
)
from netflip.manifest import (
    OUTPUT_SCHEMA_VERSION,
    RUN_MANIFEST_FILENAME,
    RunManifest,
    build_run_manifest,
    write_run_manifest,
)
from netflip.model_adapter import ModelAdapter, PerturbableTensor
from netflip.pytorch_adapter import PyTorchModelAdapter
from netflip.pytorch_bfa import (
    GradientBfaPbsCandidateScorer,
    build_gradient_bfa_pbs_candidate_scorer,
)
from netflip.runtime_device import (
    ResolvedTorchDevice,
    RuntimeDeviceUnavailableError,
    TorchDeviceRequest,
    resolve_torch_device,
)
from netflip.soft_error import (
    FAILURE_CRITERION_STOP_REASON,
    FAULT_BUDGET_STOP_REASON,
    MODEL_STATE_BITS_ARTIFACT_KIND,
    SIGNED_INT8_TWO_COMPLEMENT_REPRESENTATION,
    SOFT_ERROR_SCENARIO_TYPE,
    UNIFORM_ELIGIBLE_BIT_STRATEGY_NAME,
    EligibleBitPopulation,
    FailureCriterion,
    FaultBudget,
    MetricEvaluator,
    SoftErrorRunResult,
    UniformEligibleBitSelection,
    run_uniform_random_soft_error_baseline,
    sample_uniform_eligible_bit,
)
from netflip.summary import (
    RUN_SUMMARY_CSV_FILENAME,
    RUN_SUMMARY_JSON_FILENAME,
    RunSummary,
    build_run_summary,
    write_run_summary,
    write_run_summary_csv,
    write_run_summary_json,
)
from netflip.trace import (
    CANDIDATE_TRACE_FILENAME,
    PERTURBATION_TRACE_FILENAME,
    CandidateTraceEntry,
    PerturbationTraceEntry,
    candidate_trace_path,
    write_candidate_trace,
    write_perturbation_trace,
)

try:
    __version__ = version("netflip")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "ATTACK_BUDGET_STOP_REASON",
    "ATTACK_SCENARIO_TYPE",
    "BFA_PBS_STRATEGY_NAME",
    "CANDIDATE_TRACE_FILENAME",
    "ELIGIBLE_BITS_EXHAUSTED_STOP_REASON",
    "EXPERIMENT_SPEC_SCHEMA_VERSION",
    "FAILURE_CRITERION_STOP_REASON",
    "FAULT_BUDGET_STOP_REASON",
    "GROUND_TRUTH_TARGET_POLICY",
    "INT8_BIT_WIDTH",
    "INT8_MAX",
    "INT8_MIN",
    "INT8_MODULUS",
    "INT8_SIGN_BIT_MASK",
    "MAXIMIZE_CROSS_ENTROPY_OBJECTIVE",
    "MODEL_STATE_BITS_ARTIFACT_KIND",
    "NO_IMPROVING_CANDIDATE_STOP_REASON",
    "OUTPUT_SCHEMA_VERSION",
    "PERTURBATION_TRACE_FILENAME",
    "RUN_MANIFEST_FILENAME",
    "RUN_SUMMARY_CSV_FILENAME",
    "RUN_SUMMARY_JSON_FILENAME",
    "SIGNED_INT8_TWO_COMPLEMENT_REPRESENTATION",
    "SOFT_ERROR_SCENARIO_TYPE",
    "UINT8_MAX",
    "UNIFORM_ELIGIBLE_BIT_STRATEGY_NAME",
    "BenchmarkModelSpec",
    "BfaPbsCandidatePlan",
    "BfaPbsCandidateScore",
    "BfaPbsRunResult",
    "BfaPbsScenarioSpec",
    "BitMetadata",
    "BitRole",
    "CandidateTraceEntry",
    "CheckpointSpec",
    "CifarResNet20ArtifactPreparationOutput",
    "CifarResNet20QuantizedArtifact",
    "DatasetSpec",
    "EligibleBitPopulation",
    "ExperimentSpec",
    "FailureCriterion",
    "FaultBudget",
    "FaultBudgetSpec",
    "GradientBfaPbsCandidateScorer",
    "MetricEvaluator",
    "ModelAdapter",
    "ObjectiveEvaluator",
    "PerTensorScale",
    "PerTensorScaleMetadata",
    "PerturbableTensor",
    "PerturbationTraceEntry",
    "PyTorchModelAdapter",
    "QuantizationSpec",
    "RandomSoftErrorScenarioSpec",
    "ResolvedTorchDevice",
    "RunManifest",
    "RunSummary",
    "RuntimeDeviceUnavailableError",
    "SignedInt8TwoComplementCodec",
    "SoftErrorRunResult",
    "TorchDeviceRequest",
    "UniformEligibleBitSelection",
    "__version__",
    "build_gradient_bfa_pbs_candidate_scorer",
    "build_run_manifest",
    "build_run_summary",
    "candidate_trace_path",
    "load_cifar_resnet20_quantized_artifact",
    "load_experiment_spec",
    "load_per_tensor_scale_metadata",
    "parse_experiment_spec",
    "prepare_cifar_resnet20_artifacts",
    "quantize_cifar_resnet20_state_dict",
    "resolve_torch_device",
    "run_bfa_pbs_attack_strategy",
    "run_uniform_random_soft_error_baseline",
    "sample_uniform_eligible_bit",
    "score_bfa_pbs_candidates",
    "validate_bfa_pbs_scenario_config",
    "write_candidate_trace",
    "write_per_tensor_scale_metadata",
    "write_perturbation_trace",
    "write_run_manifest",
    "write_run_summary",
    "write_run_summary_csv",
    "write_run_summary_json",
]
